### ISSUE TITLE
Metamask browser: Unable to authenticate 

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#389]
Please check attached screencast.

https://user-images.githubusercontent.com/27370604/200764023-9328339b-a8d4-4158-ac43-08e223a06d5b.mp4

+ Add Switch network message. Thanks

**Comment by srenault-meeds** [comment]
Has been fixed @hbenali can you check please?

**Comment by hbenali** [comment]
Problem persists https://user-images.githubusercontent.com/27370604/202836356-936a3ab5-0ada-4604-870f-724441e725a5.mp4

**Comment by srenault-meeds** [comment]
Ok I see. Thanks

**Comment by srenault-meeds** [comment]
Which device and version do you use?
OS + version
Metamask app

**Comment by hbenali** [comment]
Android 13 armv8-a64 (System A/B)
Metamask: v5.9.1(995)

**Comment by srenault-meeds** [comment]
Thanks

**Comment by srenault-meeds** [comment]
Fixed!
